<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Campus.Attendance.Core\Campus.Attendance.Core.csproj" />
    <ProjectReference Include="..\Campus.Attendance.Models\Campus.Attendance.Models.csproj" />
    <ProjectReference Include="..\Campus.Attendance.Services\Campus.Attendance.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
