<?xml version="1.0" encoding="utf-8"?>
<Project>

  <!-- 统一编译属性配置，所有子项目继承 -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
